# fly.toml app configuration file generated for gameplay on 2023-05-06T09:05:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "gameplay"
primary_region = "den"
kill_signal = "SIGINT"
kill_timeout = "5s"

[processes]
  app = "uvicorn gameplay_computer.web.app:app --factory --proxy-headers --forwarded-allow-ips * --host 0.0.0.0 --port 8000"
  worker = "gameplay_worker"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "den"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/health"
    protocol = "http"
