"""drop game table

Revision ID: 1df895525d34
Revises: f1aaaa8b26db
Create Date: 2023-04-26 13:17:35.010432

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1df895525d34"
down_revision = "f1aaaa8b26db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE game AS ENUM('connect4')")
    op.add_column(
        "agents",
        sa.Column("game", sa.Enum("connect4", name="game"), nullable=True),
    )
    op.execute("UPDATE agents SET game = 'connect4'")
    op.alter_column("agents", "game", nullable=False)

    op.drop_constraint("agents_game_id_user_id_agentname_key", "agents", type_="unique")
    op.drop_index("ix_agents_game_id", table_name="agents")
    op.create_index(op.f("ix_agents_game"), "agents", ["game"], unique=False)
    op.create_unique_constraint(None, "agents", ["game", "user_id", "agentname"])
    op.drop_column("agents", "game_id")

    op.add_column(
        "matches",
        sa.Column("game", sa.Enum("connect4", name="game"), nullable=True),
    )
    op.execute("UPDATE matches SET game = 'connect4'")
    op.alter_column("matches", "game", nullable=False)
    op.drop_constraint("matches_game_id_fkey", "matches", type_="foreignkey")
    op.drop_column("matches", "game_id")

    op.drop_index("ix_games_name", table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column("game_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "matches_game_id_fkey", "matches", "games", ["game_id"], ["id"]
    )
    op.drop_column("matches", "game")
    op.add_column(
        "agents",
        sa.Column("game_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "agents", type_="unique")
    op.drop_index(op.f("ix_agents_game"), table_name="agents")
    op.create_index("ix_agents_game_id", "agents", ["game_id"], unique=False)
    op.create_unique_constraint(
        "agents_game_id_user_id_agentname_key",
        "agents",
        ["game_id", "user_id", "agentname"],
    )
    op.drop_column("agents", "game")
    op.create_table(
        "games",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="games_pkey"),
    )
    op.create_index("ix_games_name", "games", ["name"], unique=False)
    # ### end Alembic commands ###
