"""match winner

Revision ID: 1e833e1bf6ee
Revises: 4e4985d80acf
Create Date: 2023-04-13 16:41:16.151767

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e833e1bf6ee"
down_revision = "4e4985d80acf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("winner", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "winner")
    # ### end Alembic commands ###
