"""Widgets table

Revision ID: 408866a4b81c
Revises: 
Create Date: 2023-04-07 17:00:03.418573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "408866a4b81c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "widgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("widgets")
    # ### end Alembic commands ###
