"""matches

Revision ID: 4e4985d80acf
Revises: 408866a4b81c
Create Date: 2023-04-13 15:28:26.401825

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e4985d80acf"
down_revision = "408866a4b81c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game", sa.String(), nullable=True),
        sa.Column("opponent", sa.String(), nullable=True),
        sa.Column("state", sa.JSON(), nullable=True),
        sa.Column("turn", sa.Integer(), nullable=True),
        sa.Column("next_player", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("match_id", sa.Integer(), nullable=True),
        sa.Column("player", sa.Integer(), nullable=True),
        sa.Column("column", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("widgets")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "widgets",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="widgets_pkey"),
    )
    op.drop_table("turns")
    op.drop_table("matches")
    # ### end Alembic commands ###
