"""agents

Revision ID: ecc49f9f55bc
Revises: 516ddfaaa55f
Create Date: 2023-05-02 16:36:47.627765

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ecc49f9f55bc"
down_revision = "516ddfaaa55f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_deployment",
        sa.Column("agent_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("healthy", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_table(
        "agent_history",
        sa.Column("agent_id", sa.BigInteger(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("draws", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.add_column(
        "agents",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.execute("UPDATE agents SET created_at = NOW()")
    op.alter_column("agents", "created_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "created_at")
    op.drop_table("agent_history")
    op.drop_table("agent_deployment")
    # ### end Alembic commands ###
