"""agents

Revision ID: f1aaaa8b26db
Revises: 7fb740bc8fa0
Create Date: 2023-04-24 15:51:17.310944

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1aaaa8b26db"
down_revision = "7fb740bc8fa0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("game_id", sa.BigInteger(), nullable=True))
    op.execute("UPDATE agents SET game_id = 1")
    op.alter_column("agents", "game_id", nullable=False)
    op.add_column("agents", sa.Column("agentname", sa.String(), nullable=True))
    op.execute("UPDATE agents SET agentname = name")
    op.alter_column("agents", "agentname", nullable=False)

    op.drop_constraint("agents_user_id_name_key", "agents", type_="unique")
    op.drop_index("ix_agents_name", table_name="agents")
    op.create_index(op.f("ix_agents_game_id"), "agents", ["game_id"], unique=False)
    op.create_unique_constraint(None, "agents", ["game_id", "user_id", "agentname"])
    op.drop_column("agents", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "agents", type_="unique")
    op.drop_index(op.f("ix_agents_game_id"), table_name="agents")
    op.create_index("ix_agents_name", "agents", ["name"], unique=False)
    op.create_unique_constraint(
        "agents_user_id_name_key", "agents", ["user_id", "name"]
    )
    op.drop_column("agents", "agentname")
    op.drop_column("agents", "game_id")
    # ### end Alembic commands ###
