"""players index from 0

Revision ID: f4ed0977b4e9
Revises: 1df895525d34
Create Date: 2023-04-27 12:31:48.198727

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f4ed0977b4e9"
down_revision = "1df895525d34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("match_players_number_check", "match_players"),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
