name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check env
        run: env
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Test rust
        run: cargo test
      - name: Build deps
        run: |
          python -m pip install --upgrade \
            pip maturin tox pytest-github-actions-annotate-failures
      - name: Build package
        run: maturin build
      - name: Test python
        run: tox
