name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: gameplay
          POSTGRES_PASSWORD: gameplay
          POSTGRES_DB: gameplay
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: check env
        run: env
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Test rust
        run: cargo test
      - name: Build deps
        run: |
          python -m pip install --upgrade \
            pip maturin tox pytest-github-actions-annotate-failures
      - name: Build package
        run: maturin build
      - name: Test python
        run: tox
        env:
          TEST_DATABASE_URL: postgresql://gameplay:gameplay@localhost:5432/gameplay
